<?php

require_once dirname(__FILE__) . '/../MokC.php';

/**
 * Test class for MokC.
 * Generated by PHPUnit on 2012-04-18 at 16:05:20.
 */
class MokCTest
        extends PHPUnit_Framework_TestCase
{

    /**
     * @var MokC
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MokC('inputA','inputB');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers MokC::getReturnValue
     * @todo Implement testGetReturnValue().
     */
    public function testGetReturnValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
